ARG ALPINE_VERSION=latest

FROM alpine:${ALPINE_VERSION}

LABEL maintainer="Assa.Toolex@gmail.com"

RUN \
  apk -U --no-progress upgrade && \
  apk -U --no-progress add \
    tor \
  && \
  echo "Done."

VOLUME /etc/tor

EXPOSE 443 80 8080 1080 1081 9050 9051 9150 9151

USER tor

ENTRYPOINT [ "/usr/bin/tor" ]
