name: DockerHUB Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-alpine-latest:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for Alpine latest in 2020 year
      working-directory: components/transport/support-tor
      run: make docker-build ALPINE_VERSION=latest CIRCLE_TAG=$(date +%s)y20

  build-alpine-3_12:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for Alpine 3.12 in 2020 year
      working-directory: components/transport/support-tor
      run: make docker-build ALPINE_VERSION=3.12 CIRCLE_TAG=$(date +%s)y20
  
  build-alpine-3_9:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for Alpine 3.9 in 2020 year
      working-directory: components/transport/support-tor
      run: make docker-build ALPINE_VERSION=3.9 CIRCLE_TAG=$(date +%s)y20
