name: DockerHUB Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-stage-alpine-latest:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker stage-image for Alpine latest
      working-directory: components/transport/support-tor
      run: |
        ALPINE_VERSION=latest DOCKER_ORGANIZATION=talex DOCKER_IMAGE=support-tor-transport \
        DOCKER_IMAGE_VERSION=stage CIRCLE_TAG=$(date +%sy%Y) \
        make docker-build docker-test

    - name: Build the Docker stage-image for Alpine 3.12
      working-directory: components/transport/support-tor
      run: |
        ALPINE_VERSION=3.12 DOCKER_ORGANIZATION=talex DOCKER_IMAGE=support-tor-transport \
        DOCKER_IMAGE_VERSION=stage CIRCLE_TAG=$(date +%sy%Y) \
        make docker-build docker-test

    - name: Build the Docker stage-image for Alpine 3.9
      working-directory: components/transport/support-tor
      run: |
        ALPINE_VERSION=3.9 DOCKER_ORGANIZATION=talex DOCKER_IMAGE=support-tor-transport \
        DOCKER_IMAGE_VERSION=stage CIRCLE_TAG=$(date +%sy%Y) \
        make docker-build docker-test
